[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "arcfs-fsspec"
version = "0.1.11"
description = "GitLab ARC filesystem backend for fsspec"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
  "aiofiles",
  "aiohttp",
  "fsspec",
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-asyncio",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
